myfly/urls.py
from django.conf.urls import url
from . import views

app_name = 'myfly'
urlpatterns = [
    url(r'^$', views.TableView.as_view(), name='table'),
    url(r'^flight/(?P<pk>[0-9]+)/$', views.FlightView.as_view(),
        name='flight'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^myfly/', include('myfly.urls')),
    url(r'^myfly/', include('myfly.urls')),
    url(r'^polls/', include('polls.urls')),
]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

myfly/models.py
from django.db import models


class PlaneType(models.Model):

    class Meta:
        verbose_name = ('модель самолёта')
        verbose_name_plural = ('модели самолётов')

    choices_style = (
        (1, 'Пассажирский'),
        (2, 'Чартерный'),
        (3, 'Почтовый'),
        (4, 'Военный'),
    )

    name = models.CharField('Модель', max_length=20)
    style = models.PositiveSmallIntegerField(
        'Тип', choices=choices_style)
    seat = models.PositiveSmallIntegerField(
        'Кол-во мест', null=True, blank=True)
    manufacture = models.DateField('Дата выпуска')

    def __str__(self):
        return (self.name)


class Plane(models.Model):

    class Meta:
        verbose_name = ('самолёт в ангаре')
        verbose_name_plural = ('самолёты в ангаре')

    plane_type = models.ForeignKey(
        PlaneType, verbose_name='Модель самолёта', blank=True, null=True,
        on_delete=models.SET_NULL)
    purchase = models.DateField('Дата покупки')
    reg_numb = models.CharField('Рег. номер', max_length=6, unique=True)
    last_refit = models.DateField('Последний осмотр', null=True,
                                  blank=True)
    fly_col = models.PositiveSmallIntegerField('Кол-во полётов', null=True,
                                               blank=True)

    def __str__(self):
        return ((self.plane_type.name) + ' | ' + (self.reg_numb))


class Route(models.Model):

    class Meta:
        verbose_name = ('маршрут')
        verbose_name_plural = ('маршруты')

    name = models.CharField('Название', max_length=30,)
    number = models.CharField('Номер', max_length=6, unique=True)
    plane = models.ForeignKey('Plane', blank=True, null=True,
                              on_delete=models.SET_NULL,
                              verbose_name='Самолёт', )
    time = models.DateTimeField('Время вылета', )
    airport_out = models.ForeignKey('Airport', on_delete=models.CASCADE,
                                    related_name='outcoming_roures',
                                    verbose_name='Место вылета',)
    airport_in = models.ForeignKey('Airport', on_delete=models.CASCADE,
                                   related_name='incoming_roures',
                                   verbose_name='Место назначения',)

    def __str__(self):
        return (self.name)


class Airport(models.Model):

    class Meta:
        verbose_name = ('аэропорт')
        verbose_name_plural = ('аэропорты')

    name = models.CharField('Название', max_length=20,)
    code = models.CharField('Международный код', max_length=4,
                            null=True, blank=True)
    city = models.ForeignKey('City', on_delete=models.CASCADE,
                             verbose_name='Город',)
    international = models.BooleanField('Интернационален', default=True,)

    def __str__(self):
        text = (str(self.name) + ' ✈ ' + str(self.city) + ' | ' +
                str(self.city.country))
        if self.international:
            text += ' | ⇔'
        else:
            text += ' | ⇎'

        return text


class City(models.Model):

    class Meta:
        verbose_name = ('город')
        verbose_name_plural = ('города')

    name = models.CharField('Название', max_length=20,)
    country = models.ForeignKey('Country', on_delete=models.CASCADE,
                                verbose_name='Страна',)

    def __str__(self):
        return (self.name)


class Country(models.Model):

    class Meta:
        verbose_name = ('страна')
        verbose_name_plural = ('страны')

    name = models.CharField('Название', max_length=20, unique=True)

    def __str__(self):
        return self.name

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField('Текст вопроса', max_length=200)
    pub_date = models.DateTimeField('Дата вопроса')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField('Текст варианта', max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

myfly/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from .models import Route


class TableView(generic.ListView):
    model = Route
    template_name = 'myfly/table.html'
    context_object_name = 'routes_list'

    # def get_tableset(self):
    """Отображение списка всех рейсов"""
    #     return Route.objects.order_by('number')[:5]
    def get_tableset(self): 
        paginator = Paginator(TableView, 10)
        page = request.GET.get('page')

        try:
            routes = paginator.page(page)
        except PageNotAnInteger:
            routes = paginator.page(1)
        except EmptyPage:
            routes = paginator.page(paginator.num_pages)
        return routes



class FlightView(generic.DetailView):
    model = Route
    template_name = 'myfly/flight.html'

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone


from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now())

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html',
                      {'question': question,
                       'error_message': "No polls are available."
                       })
        pass
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

myfly/templates/myfly/flight.html
{% extends 'myfly/index.html' %}
{% block content %}
    {% if route %}
        <table cellspasing="2">
            <tr>
                <th>Название</th>
                <th>Номер</th>
                <th>Самолёт</th>
                <th>Время вылета</th>
            </tr>
            <tr class='cycle-tr1'>
                <td>{{ route.name }}</td>
                <td>{{ route.number }}</td>
                <td>{{ route.plane }}</td>
                <td>{{ route.time|date:'d M - G:i' }}</td>

            </tr>
        </table>
        <table cellspasing="2">
            <tr>
                <th>Вылет из</th>
                <th>Прилёт в</th>
            </tr>
            <tr class='cycle-tr1'>
                <td>{{ route.airport_out }}</td>
                <td>{{ route.airport_in }}</td>
            </tr>
        </table>
        <table cellspasing="2">
            <tr  class='cycle-tr2'>
                <td><a href="{% url 'myfly:table'%}">Назад</a></td>
            </tr>

        </table>


    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}



myfly/templates/myfly/index.html
{% load staticfiles %}

<!DOCTYPE html>

<html>
	<head>
		<meta charset="utf-8">
		<title>test</title>
		<link rel="stylesheet" href="{% static 'css/myfly.css' %}">
	</head>

	<body>
		<header>
			<div class="header-bg">
			</div>
		</header>
		
		<div class="content-bg">
			<div class="content-whire">
				{% block content %}
				{% endblock %}
			</div>
		</div>
	</body>
</html>

myfly/templates/myfly/table.html
{% extends 'myfly/index.html' %}
{% block content %}
	{% if routes_list %}
		<table cellspasing="2">
			    <tr>
			    	<th>Название</th>
			    	<th>Номер</th>
			    	<th>Самолёт</th>
			    	<th>Время вылета</th>
			    	<th>Вылет из</th>
			    	<th>Прилёт в</th>
			    </tr>
		{% for route in routes_list %}
			<tr class= 'tr-hover {% cycle 'cycle-tr1' 'cycle-tr2' %}' >
				<td><a href="{% url 'myfly:flight' route.id %}">{{ route.name }}</a></td>
		    	<td>{{ route.number }}</td>
		    	<td>{{ route.plane }}</td>
		    	<td>{{ route.time|date:'d M - G:i' }}</td>
		    	<td>{{ route.airport_out }}</td>
		    	<td>{{ route.airport_in }}</td>
		    </tr>
		{% endfor %}
		</table>

		<div class="pagination">
		    <span class="step-links">
		        {% if routes.has_previous %}
		            <a href="?page={{ routes.previous_page_number }}">previous</a>
		        {% endif %}

		        <span class="current">
		            Page {{ routes.number }} of {{ routes.paginator.num_pages }}.
		        </span>

		        {% if routes.has_next %}
		            <a href="?page={{ routes.next_page_number }}">next</a>
		        {% endif %}
		    </span>
		</div>

	{% else %}
	    <p>No polls are available.</p>
	{% endif %}
{% endblock %}

myfly/templates/polls/theme.html
{% load staticfiles %}

<!DOCTYPE html>

<html>
	<head>
		<meta charset="utf-8">
		<title>test</title>
		<link rel="stylesheet" href="{% static 'css/myfly.css' %}">
	</head>

	<body>
		<header>
			<div class="header-bg">
			</div>
		</header>
		
		<div class="content-bg">
			<div class="content-whire">
				{% block content %}
				{% endblock %}
			</div>
		</div>
	</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/theme.html' %}
{% block content %}


    <!-- <h1><strong>{{ question.question_text }}</strong></h1> -->

<!--     {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %} -->

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}" />
        <lable for="choice{{ forloop.counter }}">{{ choice.choice_text }}</lable><br />
        {% endfor %}
    <input type="submit" value="Голосовать" />
    </form>

{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/theme.html' %}
{% block content %}

    {% if latest_question_list%}
        <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are avalibe.</p>
    {% endif %}

{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/theme.html' %}
{% block content %}
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}  --  {{ choice.votes }} голос{{choice.votes|pluralize:"ов" }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Голосовать опять ?</a>
{% endblock %}

polls/templates/polls/theme.html
{% load staticfiles %}

<!DOCTYPE html>

<html>
	<head>
		<meta charset="utf-8">
		<title>test</title>
		<link rel="stylesheet" href="{% static 'polls/style.css' %}">
	</head>

	<body>
		<header>
			<div class="header-bg">
			</div>
		</header>
		
		<div class="content-bg">
			<div class="content-whire">
				{% block content %}
				{% endblock %}
			</div>
		</div>
	</body>
</html>